painting/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('upload/', views.upload_painting, name='upload'),
    path('register/',views.register,name='register'),
    path('loginPage/',views.loginPage,name='loginPage'),
    path('logoutPage/',views.logoutPage,name='logoutPage'),
    path('', views.home,name='home'),
    path('explore/', views.painting_list,name='list'),
    path('detail/<int:pk>/',views.painting_detail,name='detail'),
    path('search/',views.painting_search,name='search'),
    path('blog/',views.blog,name='blog'),
    path('news/',views.news,name='news'),
    path('contact/',views.contact,name='contact'),
    path('admin_list/',views.admin_list,name='admin_list'),
    path('edit_pictures/<int:pk>/',views.edit_pictures,name='edit_pictures'),
    path('update_pictures/<int:pk>/',views.update_pictures,name='update_pictures'),
    path('delete_pictures/<int:pk>/',views.delete_pictures,name='delete_pictures'),
    path('contact/',views.contact,name='contact'),
    path('profile/', views.profile, name='profile'),
    path('like/<int:pk>/', views.like, name='like'),
    path('like_delete/<int:pk>/', views.like_delete, name='like_delete'),
    path('add_comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('upload_avt/', views.upload_avt, name='upload_avt'),
]

painting_app/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('painting/', include('painting.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

painting/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from ckeditor.fields import RichTextField

# Create your models here.
#change form register
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name','password1','password2']

class Painting(models.Model):
    name = models.CharField(max_length=50)
    description = RichTextField()
    image = models.ImageField()
    upload_date = models.DateTimeField(auto_now_add=True)

class PaintingLq(models.Model):
    painting = models.ForeignKey(Painting, on_delete=models.CASCADE)
    image = models.ImageField()

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    painting = models.ForeignKey(Painting, on_delete=models.CASCADE)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    painting = models.ForeignKey(Painting, on_delete=models.CASCADE)
    cmt = models.TextField()

class avatar(models.Model):
    user_painting = models.ForeignKey(User,on_delete=models.CASCADE)
    avt = models.ImageField(upload_to='avatar')

painting/forms.py
from django import forms 
from .models import Painting, avatar
# from .models import ImageAdd
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class PaintingForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorUploadingWidget)
    class Meta:
        model = Painting
        fields = '__all__'

class PaintingUploadForm(forms.ModelForm):
    class Meta:
        model = Painting
        fields = ['name', 'description','image']


class PaintingUpdateForm(forms.ModelForm):
    class Meta:
        model = Painting
        fields = '__all__'

class avatar_user(forms.ModelForm):
    class Meta:
        model = avatar
        fields = ['avt']

painting/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Painting, CreateUserForm, Like, Comment,avatar
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import PaintingUploadForm
from .forms import PaintingUpdateForm, avatar_user
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login, logout
from django.contrib import messages
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
# from .forms import PaintingSearchForm
def home(request):
    paintings = Painting.objects.all()
    return render(request,'pages/home.html',{'paintings':paintings})

def blog(request):
    paintings = Painting.objects.all()
    return render(request,'pages/blog.html',{'paintings':paintings})

def news(request):
    paintings = Painting.objects.all()
    return render(request,'pages/news.html',{'paintings':paintings})
    
def contact(request):
    paintings = Painting.objects.all()
    return render(request,'pages/contact.html',{'paintings':paintings})

def painting_list(request):
    paintings = Painting.objects.all()
    if request.user.is_authenticated:
        paintings_like = Like.objects.filter(user=request.user)
        return render(request,'pages/painting_list.html',{'paintings':paintings, "paintings_like": paintings_like})
    return render(request,'pages/painting_list.html',{'paintings':paintings})

@login_required
@user_passes_test(lambda a: a.is_staff)
def admin_list(request):
    paintings = Painting.objects.all()
    return render(request,'pages/admin_list.html',{'paintings':paintings})


def delete_pictures(request,pk):
    paintings = get_object_or_404(Painting,pk=pk)
    if request.method == 'POST':
        paintings.delete()
    return render(request,'pages/delete_pictures.html',{'paintings':paintings})


def edit_pictures(request,pk):
    painting = get_object_or_404(Painting,pk=pk)
    paintings = Painting.objects.all()
    return render(request,'pages/edit_pictures.html',{'painting':painting, 'paintings':paintings})

def update_pictures(request,pk):
    painting = get_object_or_404(Painting,pk=pk)
    form = PaintingUpdateForm(request.POST,instance=painting)
    if form.is_valid:
        form.save()
        messages.success(request,"Sửa thành công")
        return redirect('list')
    return render(request,'pages/edit_pictures.html',{ 'painting':painting})


def painting_detail(request,pk):
    painting = get_object_or_404(Painting,pk=pk)
    comments = reversed(Comment.objects.all())
    paintings = Painting.objects.all()
    if request.user.is_authenticated:
        is_user = request.user
        return render(request,'pages/paiting_detail.html',{'painting':painting, 'paintings':paintings, 'comments': comments, 'is_user': is_user})
    return render(request,'pages/paiting_detail.html',{'painting':painting, 'paintings':paintings, 'comments': comments})

@login_required
@user_passes_test(lambda u: u.is_staff)
def upload_painting(request):
    paintings = Painting.objects.all()
    if request.method == 'POST':
        form = PaintingUploadForm(request.POST,request.FILES) 
        if form.is_valid():
            form.save()
            return redirect('list')
    else:
        form = PaintingUploadForm()
    
    return render(request,'pages/upload.html',{'form':form,'paintings':paintings})

@login_required
def upload_avt(request):
    if request.method == 'POST':
        form = avatar_user(request.POST,request.FILES)
        if form.is_valid():
            avatars = avatar.objects.all()
            Avt = avatars.filter(user_painting = request.user)
            if not Avt:
                avatar_obj = form.save(commit=False)
                avatar_obj.user_painting = request.user
                avatar_obj.save()
            else:
               formUpdateAvt = avatar_user(request.POST,request.FILES, instance= Avt.first())
               if  formUpdateAvt.is_valid:
                   formUpdateAvt.save()
            return redirect('profile')
    else:
        form = avatar_user()
    return render (request,'pages/upload_Avt.html', {'form':form} )

# def painting_search(request):
#     form = PaintingSearchForm(request.GET)
#     if form.is_valid():
#         query = form.cleaned_data['query']
#         name = form.cleaned_data['name']
#         if name:
#             paintings = Painting.objects.filter(
#                 name__icontains=query,
#                 name=name
#             )
#         else:
#             paintings = Painting.objects.filter(
#                 name__icontains=query
#             )
#         return render(request, 'pages/painting_search.html', {'paintings': paintings})
#     else:
#         return render(request, 'pages/painting_search.html')
#     form = PaintingSearchForm(request.GET)
def painting_search(request):
    # form = PaintingSearchForm(request.GET)
    if 'query' in request.GET:
        query = request.GET.get('query')
        # paintings = Painting.objects.filter(name__icontains = query)
        multiple_query = Q(Q(name__icontains=query) | Q(upload_date__icontains=query))
        paintings = Painting.objects.filter(multiple_query)
        return render(request, 'pages/painting_search.html', {'paintings': paintings})
    else:
        paintings = Painting.objects.all()
        context = {
            'paintings': paintings 
        }
    return render(request, 'pages/painting_search.html',context)
        
def contact(request):
    return render(request, 'pages/contact.html')       

def register(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('loginPage')
    context = {'form' : form}
    return render(request, 'pages/register.html', context)  

def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password )
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'user or password not correct!')
    context = {}
    return render(request, 'pages/login.html', context)  

def logoutPage(request):
    logout(request)
    return redirect('loginPage')

def profile(request):
    painting_likes = Like.objects.filter(user=request.user)
    avatars = avatar.objects.filter(user_painting=request.user)
    return render(request, 'pages/profile_user.html', {'painting_likes':painting_likes, 'avatars' :  avatars})  

def like(request, pk):
    pain = get_object_or_404(Painting, pk=pk)
    like = Like(user=request.user, painting=pain)
    like.save()
    return redirect('list')

def like_delete(request, pk):
    pain = get_object_or_404(Painting, pk=pk)
    like = get_object_or_404(Like, user=request.user, painting=pain)
    like.delete()
    return redirect('list')
        
def add_comment(request, pk):
    try: 
        if(request.method == 'POST'):
            pain = get_object_or_404(Painting, pk=pk)
            #vì request.body trả về chuỗi dạng byte nên phải chuyển thành dạng utf8
            cmt_req = json.loads(request.body.decode('utf-8'))
            print(request.body)
            print(cmt_req)
            new_cmt = Comment(user=request.user, painting=pain, cmt=cmt_req.get('cmt'))
            new_cmt.save()
            res_data = {
                'username': request.user.username
            }
            res = {'messages': 'success', 'res_data': res_data}
            return JsonResponse(res)
    except Exception as e:  
         return JsonResponse({'message': 'error', 'error': str(e)})

painting/templates/pages/admin_list.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %} 
  Upload picture
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'admin_list.css' %}" >
{% endblock link %}

{% block content %}
  <div class="admin_list">
    <h2 class="title-list">Danh sách tranh</h2>
    <table class="upload-table">
        <tr>
            <td class="tb-td-name">Tên tranh</td>
            <td class="tb-td-date">Ngày đăng tranh</td>
            <td class="tb-td-description">Mô tả</td>
            <td class="tb-td-control" >Chức năng</td>
        </tr>
        {% for painting in paintings %}
            <tr>
                <td class="tb-td-name"><a href="{% url 'detail' pk=painting.id %}">{{ painting.name }}</a></td>
                <td class="tb-td-date"><p class="dt-ct-date">{{ painting.upload_date }}</p></td>
                <td class="tb-td-description"><p>{{ painting.description }}</p></td>
                <td class="tb-td-control" >
                    <ul class="control-pictures">
                        <li><a href="{% url 'edit_pictures' pk=painting.id %}" class="edit-picture"><i class="fa-solid fa-pen"></i>Sửa</a></li>
                        <li><a href="{% url 'delete_pictures' pk=painting.id %}" class="delete-picture" ><i class="fa-solid fa-trash-can"></i>Xóa</a></li>
                        {% comment %} <div class="notification-delete">
                            <p>Bạn có chắc chắn muốn xóa?</p>
                            <ul>
                                <li><a href="{% url 'delete_pictures' pk=painting.id %}" class="delete-picture" >Tiếp tục xóa</a></li>
                                <li><button class="noti-exit">Thoát</button></li>
                            </ul>
                        </div> {% endcomment %}
                    </ul>
                </td>
            </tr>

        {% endfor %}
    </table>
</div>

{% endblock %}

painting/templates/pages/contact.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %}Contact{% endblock %}

{% block link %}
      <link rel="stylesheet" href="{% static 'contact.css' %}" >
{% endblock link %}

{% block content %}
 <section id="contact">
  <h1 class="section-header">LIÊN HỆ</h1>
  <div class="contact-wrapper">
  <!-- Left contact page --> 
    <form id="contact-form" class="form-horizontal" role="form">
       
      <div class="form-group">
        <div class="col-sm-12">
          <input type="text" class="form-control" id="name" placeholder="NAME" name="Tên" value="" required>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <input type="email" class="form-control" id="email" placeholder="EMAIL" name="email" value="" required>
        </div>
      </div>

      <textarea class="form-control" rows="10" placeholder="MESSAGE" name="message" required></textarea>
      
      <button class="btn btn-primary send-button" id="submit" type="submit" value="SEND">
        <div class="alt-send-button">
          <i class="fa fa-paper-plane"></i><span class="send-text">SEND</span>
        </div>
      
      </button>
      
    </form>
  <!-- Left contact page --> 
      <div class="direct-contact-container">

        <ul class="contact-list">
          <li class="list-item"><i class="fa fa-map-marker fa-2x"><span class="contact-text place">254 Hoang Quoc Viet, Co Nhue 1, Bac Tu Liem, Ha Noi</span></i></li>
          
          <li class="list-item"><i class="fa fa-phone fa-2x"><span class="contact-text phone"><a href="tel:1-212-555-5555" title="Give me a call">+ 256 879 123</a></span></i></li>
          
          <li class="list-item"><i class="fa fa-envelope fa-2x"><span class="contact-text gmail"><a href="mailto:#" title="Send me an email">supportpaiting@gmail.com</a></span></i></li>
          
        </ul>

        <hr>
        <ul class="social-media-list">
          <li><a href="#" target="_blank" class="contact-icon">
            <i class="fa-brands fa-facebook"></i></a>
          </li>
          <li><a href="#" target="_blank" class="contact-icon">
            <i class="fa-brands fa-twitter"></i></a>
          </li>
          <li><a href="#" target="_blank" class="contact-icon">
            <i class="fa-brands fa-github"></i></a>
          </li>
          <li><a href="#" target="_blank" class="contact-icon">
            <i class="fa-brands fa-tiktok"></i></a>
          </li>       
        </ul>
        <hr>

        <div class="copyright">&copy; ALL OF THE RIGHTS RESERVED</div>

      </div>
    
  </div>
  
</section>  
  
  
{% endblock %}

painting/templates/pages/delete_pictures.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %} 
{{ paintings.name }}
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'delete_pictures.css' %}" >
    <link rel="stylesheet" href="{% static 'painting_detail.css' %}" > 

{% endblock link %}

{% block content %}

  <form method="post" enctype="multipart/form-data" class="upload-content">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="delete_pictures">
      <div class="detail">
        <div class="detail-content">
                <img src="{{ paintings.image.url }}" class="detail-img" alt="">
                <h3>{{ paintings.name }}</h3>
                <p class="dt-ct-date">Ngày đăng tải: {{ paintings.upload_date }}</p>
            <p> Mô tả: {{ paintings.description }}</p>
        </div>
      </div>
      <div class="delete">
        <div class="delete-question">
          <p>Bạn có chắc muốn xóa tranh?</p>
          <div class="delete-control">
            <a href="{%url 'admin_list' %}">Thoát</a>
            <button type="submit">Xóa</button>
          </div>
        </div>   
      </div>
    </div>

  </form> 


{% endblock %}

painting/templates/pages/edit_pictures.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %} 
{{ painting.name }}
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'edit_pictures.css' %}" >
    <link rel="stylesheet" href="{% static 'upload.css' %}" > 
{% endblock link %}

{% block content %}
  <div class="upload">
    <h2>Chỉnh sửa</h2>
    <div class="upload-main">
      <div class="upload-a">
        <form method="post" enctype="multipart/form-data" class="upload-content" action="http://127.0.0.1:8000/painting/update_pictures/{{painting.id}}/">
          {% csrf_token %}
          <p>
            <label for="id_name">Tên tranh:</label>
            <input type="text" name="name" maxlength="50" required="" id="id_name" value="{{ painting.name }}">
            </p>
          <p>
            <label for="id_description">Mô tả:</label>
            <textarea name="description" cols="40" rows="10" required="" id="id_description">{{ painting.description }}</textarea>
            </p>
          <p>
            <label for="id_image">Ảnh tranh:</label>
            {% if painting.image%}
              <img src="{{ painting.image.url }}" alt="" class ="edit_pictures">
            {% endif %}
            <input type="file" name="image" accept="image/*" required="" id="id_image" value="{{ painting.image.url }}">
          </p>
          <p>
            <label for="id_image">Ảnh liên quan:</label>
            {% if painting.image%}
              <img src="{{ painting.imagelq.url }}" alt="" class ="edit_pictureslq">
            {% endif %}
            <input type="file"  multiple name="image" accept="image/*" required="" id="id_image" value="{{ painting.image.url }}">
          </p>
          <button type="submit">Cập nhật</button>
        </form>
      </div>   
      <div class="list-update">
        <p class="list-title">Danh sách tranh</p>
        <hr>
        <div class="list-update-content">
          {% for painting in paintings %}
          <a href="{% url 'detail' pk=painting.id %}">{{ painting.name }}</a> <br>
          {% endfor %}
        </div>
      </div> 
    </div>
  </div>
{% endblock %}

painting/templates/pages/login.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %} 
  login
{% endblock %}

{% block link %} 
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'login.css' %}">
  {% comment %} https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp {% endcomment %}
{% endblock %}

{% block content %}
      <section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Login</p>

                <form class="mx-1 mx-md-4" method="POST">
                  {% csrf_token %}
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="text" id="form3Example1c" class="form-control" name="username"/>
                      <label class="form-label" for="form3Example1c">Your UserName</label>
                    </div>
                  </div>

                  

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="password" id="form3Example4c" class="form-control" name="password"/>
                      <label class="form-label" for="form3Example4c">Password</label>
                    </div>
                  </div>

                 <div class="form-check d-flex justify-content-center mb-5">
                      <a href="{% url 'register' %}">Create a account</a>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Login</button>
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}
{% block link_js %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
 {% endblock %}

painting/templates/pages/painting_search.html
{% extends "pages/base.html" %}
{% load static %}  
{% block title %} 
    {{painting.name}}
{% endblock %}
{% block content %}
{% block link %} 
    <link rel="stylesheet" href="{% static 'painting_search.css' %}" > 
{% endblock %}
<div class="detail">
    <p>Kết quả tìm kiếm:</p>
    <div class="detail-search">
    {% for painting in paintings %}
        <div class="row list-picture row-search">
            <div class="col col-third picture-overview search-pt">
                <a href="{% url 'detail' pk=painting.id %}" ><img src="{{ painting.image.url }}" class="over-img" alt=""></a>
                <div class="over-des">
                    <p> Name: {{ painting.name }}</p>
                    <p> Date upload: {{ painting.upload_date }}</p>
                </div>
            <a href="{% url 'detail' pk=painting.id %}" class="over-click">Xem chi tiết  <i class="fa-solid fa-arrow-right"></i></a>   
            </div>
        </div>   
    {% endfor %}
    </div>
    
</div>
{% endblock %}

painting/templates/pages/paiting_detail.html
{% extends "pages/base.html" %}
{% load static %}  
{% block title %} 
    chi tiết
{% endblock %}

{% block link %} 
    <link rel="stylesheet" href="{% static 'painting_detail.css' %}" > 
{% endblock %}

{% block content %}
<div class="detail">
    <div class="detail-content">
            <img src="{{ painting.image.url }}" class="detail-img" alt="">
            <h3>{{ painting.name }}</h3>
            <p class="dt-ct-date">Ngày đăng tải: {{ painting.upload_date }}</p>
        
        <p> Mô tả: {{ painting.description }}</p>

        <div class="input-group mb-3">
            <img src="{% static 'image/logo.png' %}" alt="" class="user-image">
            <input id="comment" type="text" class="form-control" placeholder="Nhập bình luận" aria-label="Recipient's username" aria-describedby="button-addon2">
            {% if is_user %}
                <button onclick="addComment('{{ painting.id }}')" class="btn btn-outline-secondary" type="button" id="button-addon2">Bình luận</button>
            {% else %}
                <button onclick="commentNoUser()" class="btn btn-outline-secondary" type="button" id="button-addon2">Bình luận</button>
            {% endif %}
        </div>

        <div class="comments">
            <h2>Các bình luận</h2>
            <ul class="list-group">
                <li class="cmt cmt_tam"></li>
                {% for comment in comments %}
                    {% if comment.painting.id == painting.id %}
                        <li class="cmt">
                            <div class="cmt-par">
                                <img src="{% static 'image/logo.png' %}" alt="" class="user-image">
                                <div class="cmt-detail">
                                    <h4>{{ comment.user }}</h4> 
                                    <p>{{ comment.cmt }}</p>
                                </div>
                                <i class="bi bi-three-dots-vertical"></i>
                            </div>
                            <div class="cmt-add">
                                <span>Thích</span>
                                <span>Trả lời</span>
                                <span>5 giờ</span>
                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        
    </div>
    <div class="list-update">
        <p class="list-title">Danh sách tranh</p>
        <hr>
        <div class="list-update-content">
        {% for painting in paintings %}
        <a href="{% url 'detail' pk=painting.id %}">{{ painting.name }}</a> <br>
        {% endfor %}
        </div>
    </div>
</div>
<script src="{% static 'js/painting_detail.js' %}"></script>
{% endblock %}

painting/templates/pages/upload_Avt.html
{% extends "pages/base.html" %}
{% load static %}

{% block title %} 
  Upload Avatar
{% endblock %}
{% block link %} 
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap");
  @import url('https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap');

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Poppins", sans-serif;
}

.container {
  height: 100vh;
  width: 100%;
  align-items: center;
  display: flex;
  justify-content: center;
  background-color: #fcfcfc;
}

.card {
  border-radius: 10px;
  box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.3);
  width: 600px;
  height: 300px;
  background-color: #ffffff;
  padding: 10px 30px 40px;
}

.card h3 {
  font-size: 22px;
  font-weight: 600;
  
}

.drop_box {
  margin: 10px 0;
  padding: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  border: 3px dotted #a3a3a3;
  border-radius: 5px;
}

.drop_box h4 {
  font-size: 16px;
  font-weight: 400;
  color: #2e2e2e;
}

.drop_box p {
  margin-top: 10px;
  margin-bottom: 20px;
  font-size: 12px;
  color: #a3a3a3;
}

.btn {
  text-decoration: none;
  background-color: #005af0;
  color: #ffffff;
  padding: 10px 20px;
  border: none;
  outline: none;
  transition: 0.3s;
}

.btn:hover{
  text-decoration: none;
  background-color: #ffffff;
  color: #005af0;
  padding: 10px 20px;
  border: none;
  outline: 1px solid #010101;
}
.form input {
  margin: 10px 0;
  width: 100%;
  background-color: #e2e2e2;
  border: none;
  outline: none;
  padding: 12px 20px;
  border-radius: 4px;
}

 
  </style>
{% endblock %}

{% block content %}
  {% comment %} <div class="upload">
    <h2>Đăng đại diện</h2>
    <div class="upload-a">
      <form method="post" enctype="multipart/form-data" class="upload-content">
        {% csrf_token %}
        <input type="file" name="avt" accept="image/*" required="" id="id_avt">
        <button type="submit">Save</button>
      </form>
    </div>   
  </div> {% endcomment %}

  
  <form action="" method="POST" enctype="multipart/form-data" class="upload-content">
  
    <div class="container">
      <div class="card">
        <h3>Upload Files</h3>
        <div class="drop_box">
          <header>
            <h4>Select File here</h4>
          </header>
          <p>Files Supported:JPG, JPEG, PNG,... </p>
          {% csrf_token %}
          <input type="file" name="avt"  accept="image/*"  required=""  id="id_avt" >
          <button type="submit" class="btn" style="margin-top:15px;">submit</button>
        </div>

      </div>
    </div>
    </form>
 


{% endblock %}

{% block link_js %}
  {% comment %} <script src="{% static 'js/uploaf_avt.js' %}"></script> {% endcomment %}
{% endblock link_js %}